### PR TITLE
Update for python 3.x compatibility

### PR DESCRIPTION
**Pull request by Fenkiou**
To use it with python 3.x :
from pymill import pymill

p = pymill.Pymill('YOUR_PRIVATE_KEY')

### CODE REVIEW

**Comment by kliment** [comment]
Does this still correctly handle unicode strings with py2.x?

**Comment by Fenkiou** [comment]
Hum i don't know, i'm only using it with python 3.2 and 3.3.

**Comment by kliment** [comment]
Yes, that's the thing. Changing unicode() to str() will break unicode 
strings in py2.x which everyone except you is using.

**Comment by Fenkiou** [comment]
That's why i created a python3 branch.

**Comment by kliment** [comment]
Yes, which is fine but you're asking me to pull it into master.

**Comment by Fenkiou** [comment]
Oh yes, i know it, i hoped that you can create another branch and change my pull request to the other branch.

**Comment by kliment** [comment]
I just made a py3 branch, can you retarget your pull request to that?

**Comment by Fenkiou** [comment]
Yep, done. :)

i don't know how to delete this request, sorry.

**Pull request closed without merging**
